// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteData.proto

package org.culiu.data.framework.protobuf;

public final class RemoteData {
  private RemoteData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OriDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.culiu.data.framework.protobuf.OriData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string strategy = 1;</code>
     */
    boolean hasStrategy();
    /**
     * <code>required string strategy = 1;</code>
     */
    String getStrategy();
    /**
     * <code>required string strategy = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrategyBytes();

    /**
     * <code>required string common_fea_key = 2;</code>
     */
    boolean hasCommonFeaKey();
    /**
     * <code>required string common_fea_key = 2;</code>
     */
    String getCommonFeaKey();
    /**
     * <code>required string common_fea_key = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommonFeaKeyBytes();

    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    java.util.List<String>
        getNonComFeaKeyListList();
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    int getNonComFeaKeyListCount();
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    String getNonComFeaKeyList(int index);
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    com.google.protobuf.ByteString
        getNonComFeaKeyListBytes(int index);
  }
  /**
   * Protobuf type {@code org.culiu.data.framework.protobuf.OriData}
   */
  public  static final class OriData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.culiu.data.framework.protobuf.OriData)
      OriDataOrBuilder {
    // Use OriData.newBuilder() to construct.
    private OriData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OriData() {
      strategy_ = "";
      commonFeaKey_ = "";
      nonComFeaKeyList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OriData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              strategy_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              commonFeaKey_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                nonComFeaKeyList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              nonComFeaKeyList_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          nonComFeaKeyList_ = nonComFeaKeyList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_OriData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_OriData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.culiu.data.framework.protobuf.RemoteData.OriData.class, org.culiu.data.framework.protobuf.RemoteData.OriData.Builder.class);
    }

    private int bitField0_;
    public static final int STRATEGY_FIELD_NUMBER = 1;
    private volatile Object strategy_;
    /**
     * <code>required string strategy = 1;</code>
     */
    public boolean hasStrategy() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string strategy = 1;</code>
     */
    public String getStrategy() {
      Object ref = strategy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strategy_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strategy = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrategyBytes() {
      Object ref = strategy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        strategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMON_FEA_KEY_FIELD_NUMBER = 2;
    private volatile Object commonFeaKey_;
    /**
     * <code>required string common_fea_key = 2;</code>
     */
    public boolean hasCommonFeaKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string common_fea_key = 2;</code>
     */
    public String getCommonFeaKey() {
      Object ref = commonFeaKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commonFeaKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string common_fea_key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommonFeaKeyBytes() {
      Object ref = commonFeaKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commonFeaKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NON_COM_FEA_KEY_LIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList nonComFeaKeyList_;
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNonComFeaKeyListList() {
      return nonComFeaKeyList_;
    }
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    public int getNonComFeaKeyListCount() {
      return nonComFeaKeyList_.size();
    }
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    public String getNonComFeaKeyList(int index) {
      return nonComFeaKeyList_.get(index);
    }
    /**
     * <code>repeated string non_com_fea_key_list = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNonComFeaKeyListBytes(int index) {
      return nonComFeaKeyList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStrategy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommonFeaKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strategy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commonFeaKey_);
      }
      for (int i = 0; i < nonComFeaKeyList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nonComFeaKeyList_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strategy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commonFeaKey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < nonComFeaKeyList_.size(); i++) {
          dataSize += computeStringSizeNoTag(nonComFeaKeyList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNonComFeaKeyListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.culiu.data.framework.protobuf.RemoteData.OriData)) {
        return super.equals(obj);
      }
      org.culiu.data.framework.protobuf.RemoteData.OriData other = (org.culiu.data.framework.protobuf.RemoteData.OriData) obj;

      boolean result = true;
      result = result && (hasStrategy() == other.hasStrategy());
      if (hasStrategy()) {
        result = result && getStrategy()
            .equals(other.getStrategy());
      }
      result = result && (hasCommonFeaKey() == other.hasCommonFeaKey());
      if (hasCommonFeaKey()) {
        result = result && getCommonFeaKey()
            .equals(other.getCommonFeaKey());
      }
      result = result && getNonComFeaKeyListList()
          .equals(other.getNonComFeaKeyListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStrategy()) {
        hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
        hash = (53 * hash) + getStrategy().hashCode();
      }
      if (hasCommonFeaKey()) {
        hash = (37 * hash) + COMMON_FEA_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getCommonFeaKey().hashCode();
      }
      if (getNonComFeaKeyListCount() > 0) {
        hash = (37 * hash) + NON_COM_FEA_KEY_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getNonComFeaKeyListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.OriData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.culiu.data.framework.protobuf.RemoteData.OriData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.culiu.data.framework.protobuf.OriData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.culiu.data.framework.protobuf.OriData)
        org.culiu.data.framework.protobuf.RemoteData.OriDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_OriData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_OriData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.culiu.data.framework.protobuf.RemoteData.OriData.class, org.culiu.data.framework.protobuf.RemoteData.OriData.Builder.class);
      }

      // Construct using org.culiu.data.framework.protobuf.RemoteData.OriData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        strategy_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        commonFeaKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nonComFeaKeyList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_OriData_descriptor;
      }

      public org.culiu.data.framework.protobuf.RemoteData.OriData getDefaultInstanceForType() {
        return org.culiu.data.framework.protobuf.RemoteData.OriData.getDefaultInstance();
      }

      public org.culiu.data.framework.protobuf.RemoteData.OriData build() {
        org.culiu.data.framework.protobuf.RemoteData.OriData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.culiu.data.framework.protobuf.RemoteData.OriData buildPartial() {
        org.culiu.data.framework.protobuf.RemoteData.OriData result = new org.culiu.data.framework.protobuf.RemoteData.OriData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strategy_ = strategy_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.commonFeaKey_ = commonFeaKey_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          nonComFeaKeyList_ = nonComFeaKeyList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.nonComFeaKeyList_ = nonComFeaKeyList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.culiu.data.framework.protobuf.RemoteData.OriData) {
          return mergeFrom((org.culiu.data.framework.protobuf.RemoteData.OriData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.culiu.data.framework.protobuf.RemoteData.OriData other) {
        if (other == org.culiu.data.framework.protobuf.RemoteData.OriData.getDefaultInstance()) return this;
        if (other.hasStrategy()) {
          bitField0_ |= 0x00000001;
          strategy_ = other.strategy_;
          onChanged();
        }
        if (other.hasCommonFeaKey()) {
          bitField0_ |= 0x00000002;
          commonFeaKey_ = other.commonFeaKey_;
          onChanged();
        }
        if (!other.nonComFeaKeyList_.isEmpty()) {
          if (nonComFeaKeyList_.isEmpty()) {
            nonComFeaKeyList_ = other.nonComFeaKeyList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureNonComFeaKeyListIsMutable();
            nonComFeaKeyList_.addAll(other.nonComFeaKeyList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStrategy()) {
          return false;
        }
        if (!hasCommonFeaKey()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.culiu.data.framework.protobuf.RemoteData.OriData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.culiu.data.framework.protobuf.RemoteData.OriData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object strategy_ = "";
      /**
       * <code>required string strategy = 1;</code>
       */
      public boolean hasStrategy() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string strategy = 1;</code>
       */
      public String getStrategy() {
        Object ref = strategy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strategy_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string strategy = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrategyBytes() {
        Object ref = strategy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          strategy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strategy = 1;</code>
       */
      public Builder setStrategy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strategy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strategy = 1;</code>
       */
      public Builder clearStrategy() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strategy_ = getDefaultInstance().getStrategy();
        onChanged();
        return this;
      }
      /**
       * <code>required string strategy = 1;</code>
       */
      public Builder setStrategyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strategy_ = value;
        onChanged();
        return this;
      }

      private Object commonFeaKey_ = "";
      /**
       * <code>required string common_fea_key = 2;</code>
       */
      public boolean hasCommonFeaKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string common_fea_key = 2;</code>
       */
      public String getCommonFeaKey() {
        Object ref = commonFeaKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            commonFeaKey_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string common_fea_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommonFeaKeyBytes() {
        Object ref = commonFeaKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          commonFeaKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string common_fea_key = 2;</code>
       */
      public Builder setCommonFeaKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        commonFeaKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string common_fea_key = 2;</code>
       */
      public Builder clearCommonFeaKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        commonFeaKey_ = getDefaultInstance().getCommonFeaKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string common_fea_key = 2;</code>
       */
      public Builder setCommonFeaKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        commonFeaKey_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList nonComFeaKeyList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNonComFeaKeyListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          nonComFeaKeyList_ = new com.google.protobuf.LazyStringArrayList(nonComFeaKeyList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNonComFeaKeyListList() {
        return nonComFeaKeyList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public int getNonComFeaKeyListCount() {
        return nonComFeaKeyList_.size();
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public String getNonComFeaKeyList(int index) {
        return nonComFeaKeyList_.get(index);
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNonComFeaKeyListBytes(int index) {
        return nonComFeaKeyList_.getByteString(index);
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public Builder setNonComFeaKeyList(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNonComFeaKeyListIsMutable();
        nonComFeaKeyList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public Builder addNonComFeaKeyList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNonComFeaKeyListIsMutable();
        nonComFeaKeyList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public Builder addAllNonComFeaKeyList(
          Iterable<String> values) {
        ensureNonComFeaKeyListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nonComFeaKeyList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public Builder clearNonComFeaKeyList() {
        nonComFeaKeyList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string non_com_fea_key_list = 3;</code>
       */
      public Builder addNonComFeaKeyListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNonComFeaKeyListIsMutable();
        nonComFeaKeyList_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.culiu.data.framework.protobuf.OriData)
    }

    // @@protoc_insertion_point(class_scope:org.culiu.data.framework.protobuf.OriData)
    private static final org.culiu.data.framework.protobuf.RemoteData.OriData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.culiu.data.framework.protobuf.RemoteData.OriData();
    }

    public static org.culiu.data.framework.protobuf.RemoteData.OriData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<OriData>
        PARSER = new com.google.protobuf.AbstractParser<OriData>() {
      public OriData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OriData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OriData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OriData> getParserForType() {
      return PARSER;
    }

    public org.culiu.data.framework.protobuf.RemoteData.OriData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.culiu.data.framework.protobuf.ResultData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string comFeaKey = 1;</code>
     */
    boolean hasComFeaKey();
    /**
     * <code>required string comFeaKey = 1;</code>
     */
    String getComFeaKey();
    /**
     * <code>required string comFeaKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getComFeaKeyBytes();

    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    java.util.List<NonComFeaKey2Score>
        getResultList();
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score getResult(int index);
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    java.util.List<? extends NonComFeaKey2ScoreOrBuilder>
        getResultOrBuilderList();
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder getResultOrBuilder(
      int index);
  }
  /**
   * Protobuf type {@code org.culiu.data.framework.protobuf.ResultData}
   */
  public  static final class ResultData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.culiu.data.framework.protobuf.ResultData)
      ResultDataOrBuilder {
    // Use ResultData.newBuilder() to construct.
    private ResultData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultData() {
      comFeaKey_ = "";
      result_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResultData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              comFeaKey_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                result_ = new java.util.ArrayList<NonComFeaKey2Score>();
                mutable_bitField0_ |= 0x00000002;
              }
              result_.add(
                  input.readMessage(org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_ResultData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_ResultData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.culiu.data.framework.protobuf.RemoteData.ResultData.class, org.culiu.data.framework.protobuf.RemoteData.ResultData.Builder.class);
    }

    private int bitField0_;
    public static final int COMFEAKEY_FIELD_NUMBER = 1;
    private volatile Object comFeaKey_;
    /**
     * <code>required string comFeaKey = 1;</code>
     */
    public boolean hasComFeaKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string comFeaKey = 1;</code>
     */
    public String getComFeaKey() {
      Object ref = comFeaKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comFeaKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string comFeaKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getComFeaKeyBytes() {
      Object ref = comFeaKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        comFeaKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private java.util.List<NonComFeaKey2Score> result_;
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    public java.util.List<NonComFeaKey2Score> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    public java.util.List<? extends NonComFeaKey2ScoreOrBuilder>
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
     */
    public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasComFeaKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, comFeaKey_);
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(2, result_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, comFeaKey_);
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.culiu.data.framework.protobuf.RemoteData.ResultData)) {
        return super.equals(obj);
      }
      org.culiu.data.framework.protobuf.RemoteData.ResultData other = (org.culiu.data.framework.protobuf.RemoteData.ResultData) obj;

      boolean result = true;
      result = result && (hasComFeaKey() == other.hasComFeaKey());
      if (hasComFeaKey()) {
        result = result && getComFeaKey()
            .equals(other.getComFeaKey());
      }
      result = result && getResultList()
          .equals(other.getResultList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasComFeaKey()) {
        hash = (37 * hash) + COMFEAKEY_FIELD_NUMBER;
        hash = (53 * hash) + getComFeaKey().hashCode();
      }
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.ResultData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.culiu.data.framework.protobuf.RemoteData.ResultData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.culiu.data.framework.protobuf.ResultData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.culiu.data.framework.protobuf.ResultData)
        org.culiu.data.framework.protobuf.RemoteData.ResultDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_ResultData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_ResultData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.culiu.data.framework.protobuf.RemoteData.ResultData.class, org.culiu.data.framework.protobuf.RemoteData.ResultData.Builder.class);
      }

      // Construct using org.culiu.data.framework.protobuf.RemoteData.ResultData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        comFeaKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_ResultData_descriptor;
      }

      public org.culiu.data.framework.protobuf.RemoteData.ResultData getDefaultInstanceForType() {
        return org.culiu.data.framework.protobuf.RemoteData.ResultData.getDefaultInstance();
      }

      public org.culiu.data.framework.protobuf.RemoteData.ResultData build() {
        org.culiu.data.framework.protobuf.RemoteData.ResultData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.culiu.data.framework.protobuf.RemoteData.ResultData buildPartial() {
        org.culiu.data.framework.protobuf.RemoteData.ResultData result = new org.culiu.data.framework.protobuf.RemoteData.ResultData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.comFeaKey_ = comFeaKey_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.culiu.data.framework.protobuf.RemoteData.ResultData) {
          return mergeFrom((org.culiu.data.framework.protobuf.RemoteData.ResultData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.culiu.data.framework.protobuf.RemoteData.ResultData other) {
        if (other == org.culiu.data.framework.protobuf.RemoteData.ResultData.getDefaultInstance()) return this;
        if (other.hasComFeaKey()) {
          bitField0_ |= 0x00000001;
          comFeaKey_ = other.comFeaKey_;
          onChanged();
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasComFeaKey()) {
          return false;
        }
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.culiu.data.framework.protobuf.RemoteData.ResultData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.culiu.data.framework.protobuf.RemoteData.ResultData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object comFeaKey_ = "";
      /**
       * <code>required string comFeaKey = 1;</code>
       */
      public boolean hasComFeaKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string comFeaKey = 1;</code>
       */
      public String getComFeaKey() {
        Object ref = comFeaKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            comFeaKey_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string comFeaKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getComFeaKeyBytes() {
        Object ref = comFeaKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          comFeaKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string comFeaKey = 1;</code>
       */
      public Builder setComFeaKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        comFeaKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string comFeaKey = 1;</code>
       */
      public Builder clearComFeaKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        comFeaKey_ = getDefaultInstance().getComFeaKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string comFeaKey = 1;</code>
       */
      public Builder setComFeaKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        comFeaKey_ = value;
        onChanged();
        return this;
      }

      private java.util.List<NonComFeaKey2Score> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = new java.util.ArrayList<NonComFeaKey2Score>(result_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder> resultBuilder_;

      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public java.util.List<NonComFeaKey2Score> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder setResult(
          int index, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder setResult(
          int index, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder addResult(org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder addResult(
          int index, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder addResult(
          org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder addResult(
          int index, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder addAllResult(
          Iterable<? extends NonComFeaKey2Score> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public java.util.List<? extends NonComFeaKey2ScoreOrBuilder>
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.getDefaultInstance());
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.getDefaultInstance());
      }
      /**
       * <code>repeated .org.culiu.data.framework.protobuf.NonComFeaKey2Score result = 2;</code>
       */
      public java.util.List<NonComFeaKey2Score.Builder>
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder>
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.culiu.data.framework.protobuf.ResultData)
    }

    // @@protoc_insertion_point(class_scope:org.culiu.data.framework.protobuf.ResultData)
    private static final org.culiu.data.framework.protobuf.RemoteData.ResultData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.culiu.data.framework.protobuf.RemoteData.ResultData();
    }

    public static org.culiu.data.framework.protobuf.RemoteData.ResultData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ResultData>
        PARSER = new com.google.protobuf.AbstractParser<ResultData>() {
      public ResultData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResultData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResultData> getParserForType() {
      return PARSER;
    }

    public org.culiu.data.framework.protobuf.RemoteData.ResultData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NonComFeaKey2ScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.culiu.data.framework.protobuf.NonComFeaKey2Score)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required double score = 2;</code>
     */
    boolean hasScore();
    /**
     * <code>required double score = 2;</code>
     */
    double getScore();
  }
  /**
   * Protobuf type {@code org.culiu.data.framework.protobuf.NonComFeaKey2Score}
   */
  public  static final class NonComFeaKey2Score extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.culiu.data.framework.protobuf.NonComFeaKey2Score)
      NonComFeaKey2ScoreOrBuilder {
    // Use NonComFeaKey2Score.newBuilder() to construct.
    private NonComFeaKey2Score(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NonComFeaKey2Score() {
      key_ = "";
      score_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NonComFeaKey2Score(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              score_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.class, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder.class);
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private volatile Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private double score_;
    /**
     * <code>required double score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double score = 2;</code>
     */
    public double getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, score_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score)) {
        return super.equals(obj);
      }
      org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score other = (org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && getKey()
            .equals(other.getKey());
      }
      result = result && (hasScore() == other.hasScore());
      if (hasScore()) {
        result = result && (
            Double.doubleToLongBits(getScore())
            == Double.doubleToLongBits(
                other.getScore()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getScore()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.culiu.data.framework.protobuf.NonComFeaKey2Score}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.culiu.data.framework.protobuf.NonComFeaKey2Score)
        org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2ScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.class, org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.Builder.class);
      }

      // Construct using org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.culiu.data.framework.protobuf.RemoteData.internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_descriptor;
      }

      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score getDefaultInstanceForType() {
        return org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.getDefaultInstance();
      }

      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score build() {
        org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score buildPartial() {
        org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score result = new org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score) {
          return mergeFrom((org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score other) {
        if (other == org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          return false;
        }
        if (!hasScore()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private double score_ ;
      /**
       * <code>required double score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double score = 2;</code>
       */
      public double getScore() {
        return score_;
      }
      /**
       * <code>required double score = 2;</code>
       */
      public Builder setScore(double value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double score = 2;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.culiu.data.framework.protobuf.NonComFeaKey2Score)
    }

    // @@protoc_insertion_point(class_scope:org.culiu.data.framework.protobuf.NonComFeaKey2Score)
    private static final org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score();
    }

    public static org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<NonComFeaKey2Score>
        PARSER = new com.google.protobuf.AbstractParser<NonComFeaKey2Score>() {
      public NonComFeaKey2Score parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NonComFeaKey2Score(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NonComFeaKey2Score> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NonComFeaKey2Score> getParserForType() {
      return PARSER;
    }

    public org.culiu.data.framework.protobuf.RemoteData.NonComFeaKey2Score getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_culiu_data_framework_protobuf_OriData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_culiu_data_framework_protobuf_OriData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_culiu_data_framework_protobuf_ResultData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_culiu_data_framework_protobuf_ResultData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RemoteData.proto\022!org.culiu.data.frame" +
      "work.protobuf\"Q\n\007OriData\022\020\n\010strategy\030\001 \002" +
      "(\t\022\026\n\016common_fea_key\030\002 \002(\t\022\034\n\024non_com_fe" +
      "a_key_list\030\003 \003(\t\"f\n\nResultData\022\021\n\tcomFea" +
      "Key\030\001 \002(\t\022E\n\006result\030\002 \003(\01325.org.culiu.da" +
      "ta.framework.protobuf.NonComFeaKey2Score" +
      "\"0\n\022NonComFeaKey2Score\022\013\n\003key\030\001 \002(\t\022\r\n\005s" +
      "core\030\002 \002(\001B\014B\nRemoteData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_culiu_data_framework_protobuf_OriData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_culiu_data_framework_protobuf_OriData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_culiu_data_framework_protobuf_OriData_descriptor,
        new String[] { "Strategy", "CommonFeaKey", "NonComFeaKeyList", });
    internal_static_org_culiu_data_framework_protobuf_ResultData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_culiu_data_framework_protobuf_ResultData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_culiu_data_framework_protobuf_ResultData_descriptor,
        new String[] { "ComFeaKey", "Result", });
    internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_culiu_data_framework_protobuf_NonComFeaKey2Score_descriptor,
        new String[] { "Key", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
